export interface HardwareItem {
  id: string;
  name: string;
  englishName: string;
  category: 'ic' | 'dis';
  subCategory?: 'giris' | 'cikis' | 'giris-cikis' | 'temel-ic' | 'genisleme' | 'guc-sogutma' | 'port';
  subCategoryTitle: string;
  shortDesc: string;
  detailedDesc: string;
  function: string;
  keySpecs: string[];
  assemblyTip: string;
  funFact: string;
  iconName: string;
  badgeColor: string;
  tags: string[];
}

export const IC_DONANIM_BIRIMLERI: HardwareItem[] = [
  {
    id: 'anakart',
    name: 'Anakart',
    englishName: 'Motherboard',
    category: 'ic',
    subCategory: 'temel-ic',
    subCategoryTitle: 'Ana Omurga ve Veri Yolu',
    shortDesc: 'Tüm donanım birimlerinin üzerine takıldığı veya bağlandığı, parçalar arası veri iletişimini sağlayan ana devre kartıdır.',
    detailedDesc: 'Bilgisayarın sinir sistemi gibidir. Üzerinde yonga seti (Chipset), CPU soketi, RAM slotları, PCIe genişleme yuvaları, M.2 yuvaları ve BIOS/UEFI çipi bulunur. Tüm parçalar birbirine anakart üzerindeki veri yolları (Bus) sayesinde bağlanır.',
    function: 'Donanım birimlerini birbirine bağlamak ve aralarındaki elektrik ve veri akışını koordine etmek.',
    keySpecs: ['Form Faktörü: ATX, Micro-ATX, Mini-ITX', 'Yonga Seti (Chipset)', 'Soket Tipi (Örn: LGA1700, AM5)', 'PCIe 4.0 / 5.0 Hatları'],
    assemblyTip: 'Kasa içine vidalamadan önce yükseltme vidalarını (stand-off) mutlaka kontrol edin; anakartın kasaya doğrudan temas edip kısa devre yapmasını önler.',
    funFact: 'Bilgisayardaki parçalar saniyede milyarlarca elektrik sinyalini anakartın katmanları arasındaki mikroskobik bakır yollar üzerinden iletir.',
    iconName: 'Cpu',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    tags: ['Anakart', 'Chipset', 'Soket', 'ATX', 'Veri Yolu']
  },
  {
    id: 'islemci',
    name: 'Merkezi İşlem Birimi (İşlemci / CPU)',
    englishName: 'Central Processing Unit (CPU)',
    category: 'ic',
    subCategory: 'temel-ic',
    subCategoryTitle: 'Hesaplama ve Beyin',
    shortDesc: 'Bilgisayarın beynidir. Tüm mantıksal, aritmetiksel ve kontrol işlemlerini saniyede milyarlarca kez gerçekleştirir.',
    detailedDesc: 'Çekirdekler (Cores), önbellek (L1, L2, L3 Cache) ve Aritmetik Mantık Birimi (ALU) gibi bölümlerden oluşur. Programların makine kodlarını okur, yorumlar ve yürütür. Saat hızı (GHz) ve çekirdek sayısı işlem gücünü belirler.',
    function: 'Yazılım komutlarını yürütmek, hesaplamalar yapmak ve diğer tüm donanımlara komut vermek.',
    keySpecs: ['Saat Hızı (GHz)', 'Çekirdek / İzlek (Core/Thread) Sayısı', 'Önbellek (Cache - L3)', 'TDP Güç Tüketimi (Watt)'],
    assemblyTip: 'İşlemciyi sokete takarken sol alt köşedeki altın renkli üçgen hizalama işaretine dikkat edin. Asla bastırmayın, nazikçe oturmalıdır.',
    funFact: 'Modern bir işlemcinin içinde tırnak büyüklüğündeki silikon parçasına 10 milyardan fazla transistör sığdırılmıştır!',
    iconName: 'Microchip',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    tags: ['İşlemci', 'CPU', 'Çekirdek', 'Önbellek', 'GHz']
  },
  {
    id: 'ram',
    name: 'Rastgele Erişimli Bellek (RAM)',
    englishName: 'Random Access Memory (RAM)',
    category: 'ic',
    subCategory: 'temel-ic',
    subCategoryTitle: 'Geçici Hızlı Bellek',
    shortDesc: 'Açık olan programların ve üzerinde çalışılan verilerin geçici olarak tutulduğu ultra hızlı çalışma alanıdır.',
    detailedDesc: 'Uçucu (Volatile) bir bellektir; yani bilgisayar kapandığında veya elektrik kesildiğinde içindeki tüm veriler silinir. İşlemcinin yavaş sabit diske gitmek yerine veriye anında mikro saniyelerde erişmesini sağlar.',
    function: 'İşlemcinin anlık ihtiyaç duyduğu verileri yüksek hızda saklayıp sunmak.',
    keySpecs: ['Kapasite (8GB, 16GB, 32GB, 64GB)', 'Tür (DDR4, DDR5)', 'Frekans (MHz / MT/s)', 'Gecikme Süresi (CL - CAS Latency)'],
    assemblyTip: 'Çift kanal (Dual Channel) performansından faydalanmak için anakart kılavuzuna göre RAM modüllerini 2. ve 4. yuvalara (A2 ve B2) takın.',
    funFact: 'RAM üzerindeki bir veriye erişmek, standart bir sabit diske göre yaklaşık 100.000 kat daha hızlıdır!',
    iconName: 'Server',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    tags: ['RAM', 'Bellek', 'Geçici Bellek', 'DDR5', 'Çift Kanal']
  },
  {
    id: 'ekran-karti',
    name: 'Ekran Kartı (GPU / Grafik Kartı)',
    englishName: 'Graphics Processing Unit (GPU)',
    category: 'ic',
    subCategory: 'genisleme',
    subCategoryTitle: 'Görsel İşleme ve 3D Render',
    shortDesc: 'Görüntü sinyallerini işleyen, 3D grafikler, oyunlar ve video düzenleme işlemlerini ekrana aktaran güçlü karttır.',
    detailedDesc: 'İşlemcinin aksine paralel hesaplamalarda binlerce küçük çekirdeğe sahiptir. Kendi özel yüksek hızlı VRAM (Video RAM - GDDR6X vb.) belleğine ve bağımsız soğutma bloğuna sahiptir. PCIe x16 yuvasına takılır.',
    function: 'Matematiksel görsel verileri piksellere dönüştürüp monitöre iletmek, yapay zeka ve 3D modellemeyi hızlandırmak.',
    keySpecs: ['VRAM Belleği (8GB, 12GB, 16GB, 24GB)', 'PCIe x16 Arayüzü', 'CUDA / Stream Çekirdek Sayısı', 'Işın İzleme (Ray Tracing)'],
    assemblyTip: 'Güçlü ekran kartları yüksek akım çeker; PSU dan gelen 8-pin PCIe veya 12VHPWR güç kablosunu tık sesi duyulana kadar tam takın.',
    funFact: 'Günümüzde ekran kartları yalnızca oyunlar için değil, yapay zeka modellerini eğitmek ve bilimsel simülasyonlar için de ana güçtür.',
    iconName: 'Tv',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    tags: ['GPU', 'Ekran Kartı', 'VRAM', 'PCIe', 'Görüntü']
  },
  {
    id: 'ssd-hdd',
    name: 'Kalıcı Depolama (SSD / HDD)',
    englishName: 'Solid State Drive & Hard Disk Drive',
    category: 'ic',
    subCategory: 'temel-ic',
    subCategoryTitle: 'Kalıcı Veri Depolama',
    shortDesc: 'İşletim sistemini, oyunları ve dosyalarınızı bilgisayar kapansa bile güvenle saklayan kalıcı hafızadır.',
    detailedDesc: 'HDD mekanik dönen manyetik disklerle çalışırken, modern SSD ler NAND flaş bellek yongalarıyla tamamen elektronik çalışır. M.2 NVMe SSD ler saniyede 7000+ MB okuma hızlarına ulaşarak bilgisayarı saniyeler içinde açar.',
    function: 'İşletim sistemi, programlar ve kullanıcı verilerini elektrik kesilse bile kalıcı olarak depolamak.',
    keySpecs: ['Form: M.2 NVMe, 2.5 inç SATA, 3.5 inç HDD', 'Okuma/Yazma Hızı (MB/s)', 'Kapasite (500GB, 1TB, 2TB, 4TB)', 'TBW Ömrü'],
    assemblyTip: 'M.2 NVMe SSD takarken anakartın vidasını fazla sıkmayın ve üzerindeki termal pedi/soğutucu bloğu mutlaka yerleştirin.',
    funFact: 'Mekanik bir HDD nin okuma kafası dönen plağa bir saç telinin kalınlığından çok daha yakın mesafede uçar!',
    iconName: 'HardDrive',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    tags: ['SSD', 'HDD', 'NVMe', 'M.2', 'Kalıcı Depolama']
  },
  {
    id: 'guc-kaynagi',
    name: 'Güç Kaynağı (PSU)',
    englishName: 'Power Supply Unit (PSU)',
    category: 'ic',
    subCategory: 'guc-sogutma',
    subCategoryTitle: 'Enerji Dönüştürücü',
    shortDesc: 'Prizden gelen 220V alternatif akımı (AC), bileşenlerin ihtiyaç duyduğu 12V, 5V, 3.3V doğru akıma (DC) dönüştürür.',
    detailedDesc: 'Tüm parçaların can damarıdır. Kalitesiz bir PSU tüm sistemi riske atabilir. 80 Plus (Bronze, Gold, Platinum) sertifikaları enerji verimliliğini gösterir. Modüler modellerde sadece ihtiyaç duyulan kablolar takılır.',
    function: 'Şebeke elektriğini bilgisayar donanımlarının güvenle kullanabileceği düşük voltajlı doğru akıma çevirmek.',
    keySpecs: ['Toplam Güç (550W, 750W, 850W, 1000W)', 'Verimlilik: 80 Plus Gold/Platinum', 'Modülerlik: Tam Modüler / Yarı Modüler', 'Koruma: OVP, OCP, SCP'],
    assemblyTip: 'PSU fanının hava alabilmesi için kasanın altındaki havalandırma ızgarasına doğru baktığından emin olun.',
    funFact: '80 Plus Gold sertifikalı bir PSU, prizden çektiği elektriğin %90 ından fazlasını kayıpsız bir şekilde sisteme aktarır.',
    iconName: 'Zap',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    tags: ['PSU', 'Güç Kaynağı', 'Watt', '80 Plus', 'Elektrik']
  },
  {
    id: 'sogutma-sistemi',
    name: 'Soğutma Sistemi (Fan & Sıvı Soğutma)',
    englishName: 'Cooling System (Air & Liquid)',
    category: 'ic',
    subCategory: 'guc-sogutma',
    subCategoryTitle: 'Termal Denge ve Isı Dağıtımı',
    shortDesc: 'İşlemci ve kasa içerisindeki sıcak havayı dışarı atarak parçaların aşırı ısınıp yavaşlamasını veya yanmasını önler.',
    detailedDesc: 'Hava soğutma (ısı boruları ve alüminyum yapraklar) veya sıvı soğutma (radyatör, pompa ve soğutucu sıvı) kullanılır. İşlemci ile soğutucu arasına mikroskobik hava boşluklarını doldurmak için mutlaka termal macun sürülür.',
    function: 'Donanım bileşenlerinin sıcaklığını güvenli çalışma limitlerinde tutmak.',
    keySpecs: ['Radyatör Boyutu (240mm, 360mm)', 'Hava Akışı (CFM)', 'Ses Seviyesi (dBA)', 'PWM Hız Kontrolü'],
    assemblyTip: 'Soğutucuyu monte etmeden önce tabanındaki şeffaf koruyucu naylonu sökmeyi ve bezelye tanesi kadar termal macun sürmeyi unutmayın!',
    funFact: 'Eğer işlemci soğutucusuz çalıştırılırsa, saniyeler içinde 100 dereceye ulaşıp güvenlik için kendini otomatik kapatır.',
    iconName: 'Fan',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    tags: ['Soğutma', 'Fan', 'Sıvı Soğutma', 'Termal Macun', 'Isı']
  },
  {
    id: 'ses-ve-ag-karti',
    name: 'Ağ ve Ses Kartları (NIC / Audio)',
    englishName: 'Network Interface Card & Sound Card',
    category: 'ic',
    subCategory: 'genisleme',
    subCategoryTitle: 'İletişim ve Multimedya',
    shortDesc: 'Bilgisayarın yerel ağa/internete bağlanmasını ve dijital ses verilerini analog hoparlör sinyallerine çevirmesini sağlar.',
    detailedDesc: 'Çoğu anakartta tümleşik (onboard) olarak yer alır; ancak profesyonel stüdyolar ve yüksek hızlı veri merkezleri için PCIe yuvasına takılan harici 10 Gigabit Ethernet veya stüdyo ses kartları tercih edilir.',
    function: 'Ağ paketlerini iletmek (Wi-Fi / Ethernet) ve ses sinyallerini işleyip aktarmak.',
    keySpecs: ['Ethernet Hızı (1Gbps, 2.5Gbps, 10Gbps)', 'Wi-Fi Standardı (Wi-Fi 6E, Wi-Fi 7)', 'Ses Kanalları (5.1, 7.1 Surround)'],
    assemblyTip: 'Wi-Fi kartı takılıysa kasa arkasındaki anten vidalarını iyi sıkın; zayıf anten kablosuz çekim gücünü ciddi oranda düşürür.',
    funFact: 'Modern Wi-Fi 7 kartları, kablosuz olarak saniyede 5 gigabitin üzerinde veri aktarabilmektedir.',
    iconName: 'Wifi',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    tags: ['Ağ Kartı', 'Ethernet', 'Wi-Fi', 'Ses Kartı', 'İletişim']
  }
];

export const DIS_DONANIM_BIRIMLERI: HardwareItem[] = [
  // GİRİŞ BİRİMLERİ (INPUT)
  {
    id: 'klavye',
    name: 'Klavye',
    englishName: 'Keyboard',
    category: 'dis',
    subCategory: 'giris',
    subCategoryTitle: 'Giriş Birimi (Input)',
    shortDesc: 'Kullanıcının harfler, sayılar ve komut tuşları ile bilgisayara veri ve yönlendirme girmesini sağlayan temel birimdir.',
    detailedDesc: 'Membran veya mekanik anahtarlı (Switch) çeşitleri bulunur. Tuşa basıldığında tuş matrisi bir elektrik sinyali üretir ve mikrodenetleyici bu sinyali karakter koduna (ASCII/Unicode) çevirerek USB üzerinden bilgisayara yollar.',
    function: 'Metin, sayı ve kontrol komutlarını bilgisayara girmek.',
    keySpecs: ['Anahtar Tipi (Mekanik, Membran)', 'Düzen (Türkçe Q, Türkçe F)', 'Bağlantı (USB, Bluetooth, 2.4GHz)'],
    assemblyTip: 'Türkçe yazım hızını artırmak ve resmi yazışmalar için F klavye veya evrensel Q klavye standartlarına dikkat edilmelidir.',
    funFact: 'F klavye, Türkçe harf kullanım sıklığı bilimsel olarak araştırılarak Türkçeye en uygun şekilde Prof. Dr. İhsan Sıtkı Yener tarafından tasarlanmıştır.',
    iconName: 'Keyboard',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    tags: ['Klavye', 'Giriş Birimi', 'Mekanik', 'Q Klavye', 'F Klavye']
  },
  {
    id: 'fare',
    name: 'Fare (Mouse)',
    englishName: 'Computer Mouse',
    category: 'dis',
    subCategory: 'giris',
    subCategoryTitle: 'Giriş Birimi (Input)',
    shortDesc: 'Ekrandaki imleci (işaretçiyi) kontrol ederek tıklama, sürükleme ve komut verme işlemlerini yapan işaretleme aygıtıdır.',
    detailedDesc: 'Optik veya lazer sensörler yüzeydeki mikroskobik detayların saniyede binlerce fotoğrafını çekerek hareket yönünü ve mesafesini hesaplar. DPI (Dots Per Inch) değeri hassasiyetini belirler.',
    function: 'Grafik arayüzde imleç yönlendirmek, seçim yapmak ve tıklamak.',
    keySpecs: ['Sensör Türü (Optik, Lazer)', 'Hassasiyet (DPI / CPI)', 'Raporlama Hızı (Polling Rate - Hz)', 'Ergonomi (Sağ/Sol el)'],
    assemblyTip: 'Doğru imleç takibi için farenin altındaki optik sensör camının temiz ve düzgün bir mousepad üzerinde kullanılması önerilir.',
    funFact: 'İlk bilgisayar faresi 1964 yılında Douglas Engelbart tarafından ahşap bir blok ve iki metal tekerlek kullanılarak yapılmıştır!',
    iconName: 'Mouse',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    tags: ['Fare', 'Mouse', 'Giriş Birimi', 'DPI', 'Optik']
  },
  {
    id: 'tarayici',
    name: 'Tarayıcı (Scanner)',
    englishName: 'Image Scanner',
    category: 'dis',
    subCategory: 'giris',
    subCategoryTitle: 'Giriş Birimi (Input)',
    shortDesc: 'Basılı fotoğrafları, belgeleri veya çizimleri optik sensörleriyle okuyarak dijital resim veya PDF formatına çevirir.',
    detailedDesc: 'Işık kaynağı belgeyi aydınlatır, yansıyan ışık aynalar ve lensler vasıtasıyla CCD veya CIS sensörlerine odaklanır. Renk tonları dijital piksellere dönüştürülerek bilgisayara aktarılır.',
    function: 'Fiziksel kağıt ve fotoğrafları bilgisayara dijital veri olarak aktarmak.',
    keySpecs: ['Çözünürlük (DPI - 1200x2400)', 'Sensör (CCD, CIS)', 'Tarama Hızı (Sayfa/Dakika)', 'OCR Desteği'],
    assemblyTip: 'Tarayıcı camı üzerindeki toz ve parmak izleri taramada çizgi veya leke oluşturur; antistatik mikrofiber bezle temizlenmelidir.',
    funFact: 'OCR (Optik Karakter Tanıma) teknolojisi sayesinde taranan bir kitaptaki metinler doğrudan kopyalanabilir Word yazısına çevrilebilir.',
    iconName: 'ScanLine',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    tags: ['Tarayıcı', 'Scanner', 'Giriş Birimi', 'DPI', 'OCR']
  },
  {
    id: 'mikrofon-ve-kamera',
    name: 'Mikrofon ve Web Kamerası',
    englishName: 'Microphone & Webcam',
    category: 'dis',
    subCategory: 'giris',
    subCategoryTitle: 'Giriş Birimi (Input)',
    shortDesc: 'Ortamdaki ses dalgalarını elektrik sinyaline, görüntüleri ise video piksellerine dönüştürerek bilgisayara aktarır.',
    detailedDesc: 'Mikrofon havadaki ses titreşimlerini diyafram aracılığıyla analog elektrik sinyaline ve ardından dijital sese çevirir. Web kamerası CMOS sensörüyle ışığı toplayıp canlı video akışı üretir.',
    function: 'Kullanıcının sesini ve görüntüsünü bilgisayara aktarmak (toplantı, kayıt vb.).',
    keySpecs: ['Kamera Çözünürlüğü (1080p FHD, 4K)', 'Kare Hızı (30/60 FPS)', 'Mikrofon Tipi (Kondenser, Dinamik)'],
    assemblyTip: 'Kamera lens kapağı mahremiyet için kullanılabilir; mikrofonun ise arka plan gürültüsü engelleyici filtresi ayarlanmalıdır.',
    funFact: 'İlk web kamerası Cambridge Üniversitesi araştırmacıları tarafından bir kahve makinesinin dolu olup olmadığını izlemek için geliştirilmiştir!',
    iconName: 'Video',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    tags: ['Mikrofon', 'Webcam', 'Giriş Birimi', 'Ses', 'Görüntü']
  },

  // ÇIKIŞ BİRİMLERİ (OUTPUT)
  {
    id: 'monitor',
    name: 'Monitör (Ekran)',
    englishName: 'Display Monitor',
    category: 'dis',
    subCategory: 'cikis',
    subCategoryTitle: 'Çıkış Birimi (Output)',
    shortDesc: 'Ekran kartından gelen video sinyallerini kullanıcıya görsel olarak yansıtan temel çıkış birimidir.',
    detailedDesc: 'IPS, VA veya OLED panel teknolojileriyle milyonlarca pikselin renk değiştirmesini sağlar. Çözünürlük (1080p, 2K, 4K), yenileme hızı (Hz) ve tepki süresi (ms) panel kalitesini belirler.',
    function: 'Bilgisayarda işlenen tüm grafik, metin ve video verilerini gözle görülebilir hale getirmek.',
    keySpecs: ['Çözünürlük (Full HD, 2K QHD, 4K UHD)', 'Yenileme Hızı (60Hz, 144Hz, 240Hz)', 'Panel Tipi (IPS, OLED, VA)', 'Girişler (HDMI, DisplayPort)'],
    assemblyTip: 'Yüksek yenileme hızı (144Hz+) almak için HDMI yerine DisplayPort kablosu tercih edilmelidir ve kablo mutlaka anakarta değil ekran kartına takılmalıdır!',
    funFact: 'Modern bir 4K monitörde gözümüzün önünde aynı anda 8.3 milyon adet bağımsız piksel ışıldamaktadır!',
    iconName: 'Monitor',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    tags: ['Monitör', 'Ekran', 'Çıkış Birimi', 'IPS', 'HDMI', 'DisplayPort']
  },
  {
    id: 'yazici',
    name: 'Yazıcı (Printer)',
    englishName: 'Computer Printer',
    category: 'dis',
    subCategory: 'cikis',
    subCategoryTitle: 'Çıkış Birimi (Output)',
    shortDesc: 'Bilgisayardaki dijital belgeleri, fotoğrafları ve çizimleri kağıt üzerine basarak somut hale getiren birimdir.',
    detailedDesc: 'Lazer yazıcılar toneri tambur ve ısıyla kağıda yapıştırırken, mürekkep püskürtmeli (Inkjet) yazıcılar mikroskobik mürekkep damlacıkları fırlatır. Sayfa başı maliyet ve baskı hızı (PPM) önemlidir.',
    function: 'Dijital ortamdaki bilgi ve belgeleri basılı kağıt çıktısına dönüştürmek.',
    keySpecs: ['Baskı Teknolojisi (Lazer, Mürekkep Püskürtmeli)', 'Baskı Hızı (PPM - Sayfa/Dk)', 'Baskı Çözünürlüğü (DPI)', 'Çift Taraflı Baskı (Duplex)'],
    assemblyTip: 'Lazer yazıcılarda toner kartuşu takılmadan önce sağa sola yavaşça sallanarak toner tozunun homojen dağılması sağlanmalıdır.',
    funFact: 'Modern 3D yazıcılar da bu ailenin bir üyesidir ve bilgisayardaki 3 boyutlu modelleri eritilmiş plastikle gerçek nesnelere çevirir.',
    iconName: 'Printer',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    tags: ['Yazıcı', 'Printer', 'Çıkış Birimi', 'Lazer', 'Toner']
  },
  {
    id: 'hoparlor-kulaklik',
    name: 'Hoparlör ve Kulaklık',
    englishName: 'Speakers & Headphones',
    category: 'dis',
    subCategory: 'cikis',
    subCategoryTitle: 'Çıkış Birimi (Output)',
    shortDesc: 'Ses kartından gelen elektriksel analog ses sinyallerini kulakla duyulabilir akustik ses dalgalarına dönüştürür.',
    detailedDesc: 'Mıknatıs ve bobin yardımıyla koni şeklindeki diyaframı titreştirerek havada ses dalgaları üretir. 3.5mm jak, USB veya Bluetooth protokolüyle bağlanır.',
    function: 'Sistem seslerini, müzikleri, oyun seslerini ve konuşmaları duyulabilir kılmak.',
    keySpecs: ['Frekans Tepkisi (20Hz - 20kHz)', 'Empedans (Ohm)', 'Kanal Sayısı (2.0 Stereo, 2.1, 7.1 Surround)', 'Bağlantı (3.5mm Jak, USB, BT)'],
    assemblyTip: 'Anakartın arkasındaki açık yeşil renkli 3.5mm jak soketi standart hoparlör ve kulaklık ses çıkışıdır.',
    funFact: 'İnsan kulağı 20 Hz ile 20.000 Hz arasındaki titreşimleri duyar; kaliteli ses cihazları tam bu aralığı bozulmasız verir.',
    iconName: 'Volume2',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    tags: ['Hoparlör', 'Kulaklık', 'Çıkış Birimi', 'Ses Çıkışı', 'Stereo']
  },
  {
    id: 'projeksiyon',
    name: 'Projeksiyon Cihazı',
    englishName: 'Projector',
    category: 'dis',
    subCategory: 'cikis',
    subCategoryTitle: 'Çıkış Birimi (Output)',
    shortDesc: 'Bilgisayar görüntüsünü güçlü bir ışık kaynağı ve mercekler aracılığıyla büyük bir perdeye veya duvara yansıtan çıkış birimidir.',
    detailedDesc: 'Sınıflarda ve konferans salonlarında toplu sunumlar için kullanılır. DLP veya 3LCD teknolojileri kullanılır. Işık gücü ANSI Lümen birimiyle ölçülür.',
    function: 'Görüntüyü kalabalık kitlelerin görebileceği dev ekran boyutuna büyüterek yansıtmak.',
    keySpecs: ['Parlaklık (ANSI Lümen)', 'Doğal Çözünürlük (1080p, 4K)', 'Kontrast Oranı', 'Lamba Ömrü (Saat)'],
    assemblyTip: 'Kullanım sonrası hemen prizden çekilmemelidir; fanın lambayı soğutması için cihazın kendi kapanma sürecini tamamlaması beklenmelidir.',
    funFact: 'Lazer projeksiyon cihazları lamba değişimi gerektirmeden 20.000 saatten fazla çalışabilir.',
    iconName: 'Projector',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    tags: ['Projeksiyon', 'Çıkış Birimi', 'Lümen', 'Sunum']
  },

  // HEM GİRİŞ HEM ÇIKIŞ BİRİMLERİ (G/Ç - I/O)
  {
    id: 'dokunmatik-ekran',
    name: 'Dokunmatik Ekran',
    englishName: 'Touchscreen',
    category: 'dis',
    subCategory: 'giris-cikis',
    subCategoryTitle: 'Giriş ve Çıkış Birimi (G/Ç)',
    shortDesc: 'Kullanıcıya hem görüntü sunan (çıkış) hem de parmak dokunuşlarını algılayıp komut alan (giriş) çift yönlü birimdir.',
    detailedDesc: 'Kapasitif dokunmatik ekranlar insan vücudunun elektriksel iletkenliğini kullanarak parmağın değdiği koordinatı anında hesaplar. Akıllı telefonlar, tabletler ve POS cihazlarında yaygındır.',
    function: 'Aynı yüzey üzerinden hem veri göstermek hem de dokunmatik giriş almak.',
    keySpecs: ['Çoklu Dokunma (Multi-touch 10 Nokta)', 'Tepki Süresi', 'Kapasitif vs Rezistif Panel'],
    assemblyTip: 'Ekran koruyucu takılırken toz kalmamasına ve dokunmatik hassasiyet kalibrasyonunun yapılmasına dikkat edilmelidir.',
    funFact: 'Modern dokunmatik ekranlar aynı anda 10 farklı parmağın hareketini bağımsız olarak takip edebilir.',
    iconName: 'Smartphone',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    tags: ['Dokunmatik Ekran', 'G/Ç', 'Giriş-Çıkış', 'Tablet']
  },
  {
    id: 'modem-router',
    name: 'Modem ve Yönlendirici (Router)',
    englishName: 'Modem & Router',
    category: 'dis',
    subCategory: 'giris-cikis',
    subCategoryTitle: 'Giriş ve Çıkış Birimi (G/Ç)',
    shortDesc: 'İnternet servis sağlayıcısından gelen sinyalleri çözer, veri indirir (giriş) ve bilgisayardan çıkan verileri internete yükler (çıkış).',
    detailedDesc: 'Modem (Modülatör-Demodülatör) analog ve fiber sinyalleri dijitale çevirir. Router ise evdeki tüm cihazlara yerel IP dağıtarak veri paketlerini doğru hedefe yönlendirir.',
    function: 'İki yönlü internet ve ağ veri trafiğini yönetmek.',
    keySpecs: ['Wi-Fi 6 / Wi-Fi 7', 'Bant Desteği (2.4GHz, 5GHz, 6GHz)', 'Gigabit LAN Portları', 'Fiber / VDSL Uyumluluğu'],
    assemblyTip: 'Modemi evin merkezi ve yüksek bir yerine koymak sinyal kalitesini belirgin şekilde artırır; kalın duvarların arkasına koyulmamalıdır.',
    funFact: 'Modem kelimesi "Modülatör" ve "Demodülatör" sözcüklerinin ilk hecelerinin birleştirilmesiyle türetilmiştir.',
    iconName: 'Radio',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    tags: ['Modem', 'Router', 'G/Ç', 'İnternet', 'Ağ', 'Wi-Fi']
  },
  {
    id: 'usb-bellek-harici-disk',
    name: 'Harici Disk ve USB Bellek',
    englishName: 'External Drive & USB Flash',
    category: 'dis',
    subCategory: 'giris-cikis',
    subCategoryTitle: 'Giriş ve Çıkış Birimi (G/Ç)',
    shortDesc: 'Bilgisayardan içine dosya aktarılabilen (çıkış) ve içindeki dosyalar bilgisayara yüklenebilen (giriş) taşınabilir depolama birimidir.',
    detailedDesc: 'Taşınabilir SSD ler ve USB flash bellekler NAND yongaları kullanır. USB Type-C veya Type-A portlarından bağlanır. Her iki yönde de okuma ve yazma yaptığı için G/Ç birimidir.',
    function: 'Verileri taşımak, yedeklemek ve cihazlar arası veri transferi yapmak.',
    keySpecs: ['Arayüz: USB 3.2 Gen 2, Thunderbolt', 'Aktarım Hızı (100MB/s - 2000MB/s)', 'Kapasite (64GB - 4TB)'],
    assemblyTip: 'Veri kaybını önlemek için USB belleği çekmeden önce işletim sisteminden "Güvenle Kaldır" seçeneğini kullanın.',
    funFact: 'İlk USB bellekler 2000 yılında piyasaya çıktığında sadece 8 Megabayt kapasiteye sahipti!',
    iconName: 'Usb',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    tags: ['USB Bellek', 'Harici Disk', 'G/Ç', 'Taşınabilir Depolama']
  },
  {
    id: 'portlar',
    name: 'Bağlantı Portları (HDMI, USB, Type-C)',
    englishName: 'I/O Ports & Connectors',
    category: 'dis',
    subCategory: 'port',
    subCategoryTitle: 'Fiziksel İletişim Arayüzleri',
    shortDesc: 'Dış donanım birimlerinin anakart ve ekran kartına bağlandığı fiziksel soket ve yuvalardır.',
    detailedDesc: 'HDMI ve DisplayPort görüntü/ses iletir; USB-A ve USB-C genel çevre birimlerini ve veri iletişimini bağlar; RJ-45 Ethernet kablolu ağ bağlantısı sağlar; 3.5mm jak ses taşır.',
    function: 'Dış aygıtlar ile bilgisayar kasası arasında fiziksel ve elektriksel veri köprüsü kurmak.',
    keySpecs: ['USB-C: 40Gbps + Güç İletimi', 'HDMI 2.1: 4K 120Hz / 8K 60Hz', 'DisplayPort 2.1', 'RJ-45 Gigabit Ethernet'],
    assemblyTip: 'Kabloları takarken yönüne dikkat edin; zorlamayın. USB-C simetrik olduğu için her iki yönde de takılabilir.',
    funFact: 'USB Type-C tek bir kablo üzerinden hem 240W elektrik şarjı hem 8K görüntü hem de yüksek hızlı veri taşıyabilir!',
    iconName: 'Cable',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    tags: ['Portlar', 'USB-C', 'HDMI', 'DisplayPort', 'RJ-45']
  }
];

export const ALL_HARDWARE = [...IC_DONANIM_BIRIMLERI, ...DIS_DONANIM_BIRIMLERI];
